#!/usr/bin/env bash
# This script transfers a file from client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking for scp
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key_path" "$file_path" "$username@$ip:~/"
