#!/usr/bin/env bash
# This script sets up an nginx web server
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
