#!/usr/bin/env bash
# This script sets up an nginx web server
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
