#!/usr/bin/env bash
# Illustrating redirection

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create redirection configuration file
sudo bash -c 'echo "server {
    listen 80;
    server_name _;

    root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}" > /etc/nginx/sites-enabled/default'

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
