#!/usr/bin/env bash
# Script to install load balancer

# Step 1: Install HAProxy
sudo apt update
sudo apt-get install --no-install-recommends -y software-properties-common
echo | sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*
sudo apt-get install -y haproxy

DOMAIN_NAME='dhelped.tech'
# Step 2: Configure HAProxy
sudo mkdir -p /etc/haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend $DOMAIN_NAME-frontend
    bind *:80
    default_backend $DOMAIN_NAME-backend

backend $DOMAIN_NAME-backend
    balance roundrobin
    server web-01 483-web-01:80 check
    server web-02 483-web-02:80 check
EOF

# Step 3: Configure HAProxy to start on boot
sudo tee -a /etc/default/haproxy > /dev/null <<EOF
ENABLED=1
EOF

# Step 4: Start HAProxy
sudo service haproxy start
