#!/usr/bin/env bash
# This script displays content of the file "/etc/passwd"
#		but only display username, user id and home directory path for the user

less /etc/passwd | while read -r LREAD
do
	echo "${LREAD}" | cut -d ":" -f1,3,6
done
