#!/usr/bin/env bash
# configure contain to run Nginx as nginx user

sudo chmod 644 /etc/nginx/nginx.conf
nginx_conf="/etc/nginx/nginx.conf"
sed -i 's/^#*user.*/user nginx;/' $nginx_conf

su nginx -c "service nginx restart"
