#!/usr/bin/env bash
# configure contain to run Nginx as nginx user

sudo chmod 644 /etc/nginx/nginx.conf
nginx_conf="/etc/nginx/nginx.conf"
sed -i 's/^#*user.*/user nginx;/' $nginx_conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
